/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#141428',
        surface: '#1C1C2E',
        'surface-2': '#232338',
        border: '#2E2E48',
        crimson: '#8B0000',
        'crimson-bright': '#B22222',
        gold: '#C9A84C',
        physical: '#22C55E',
        mental: '#60A5FA',
        financial: '#FBBF24',
        spiritual: '#C084FC',
        social: '#F472B6',
        purpose: '#F97316',
        awareness: '#14B8A6',
        teal: '#14B8A6',
        violet: '#8B5CF6',
        psychological: '#F472B6',
        cognitive: '#06B6D4',
        ontological: '#F97316',
        'text-primary': '#D4D4D8',
        'text-muted': '#6B6B84',
        'text-faint': '#44445A',
      },
      fontFamily: {
        display: ['Cinzel', 'Georgia', 'serif'],
        serif: ['Cinzel', 'Georgia', 'serif'],
        body: ['Outfit', 'system-ui', 'sans-serif'],
        mono: ['DM Mono', 'monospace'],
        sans: ['Outfit', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
