import React, { useState } from 'react';
import { useWeeklyDigest } from '../hooks/useWeeklyDigest.js';
import { formatRelativeTime } from '../utils/formatters.js';

function renderMarkdown(text) {
  if (!text) return '';
  return text
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<[hul])(.+)$/gm, (m) => (m.trim() ? `<p>${m}</p>` : ''));
}

export default function WeeklyDigest() {
  const { digest, loading, generating, generate } = useWeeklyDigest();
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="card fade-in">
      <div
        className="flex items-center justify-between cursor-pointer"
        onClick={() => setExpanded((v) => !v)}
      >
        <div className="flex items-center gap-3">
          <span style={{ color: '#C084FC' }} className="text-lg">
            ✦
          </span>
          <div>
            <h3 className="font-display font-semibold text-sm text-text-primary">
              Weekly Digest
            </h3>
            {digest && (
              <p className="text-xs text-text-muted font-mono">
                Generated {formatRelativeTime(digest.generated_at)} · Weakest:{' '}
                <span style={{ color: '#FBBF24' }}>{digest.weakest_pillar}</span>
              </p>
            )}
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={(e) => {
              e.stopPropagation();
              generate();
            }}
            disabled={generating}
            className="btn-ghost text-xs py-1"
          >
            {generating ? '⟳ Generating...' : '↺ Generate'}
          </button>
          <span className="text-text-muted text-sm">{expanded ? '▲' : '▼'}</span>
        </div>
      </div>

      {expanded && (
        <div className="mt-5 pt-5 border-t border-border slide-up">
          {loading ? (
            <div className="flex items-center gap-2 text-text-muted text-sm">
              <span className="animate-spin">⟳</span> Loading...
            </div>
          ) : digest ? (
            <>
              <div
                className="digest-content"
                dangerouslySetInnerHTML={{ __html: renderMarkdown(digest.content) }}
              />
              <p className="mt-4 text-xs text-text-muted font-mono border-t border-border pt-3">
                Generated by Claude · {digest.week_start} → {digest.week_end}
              </p>
            </>
          ) : (
            <div className="text-center py-8">
              <p className="text-text-muted text-sm mb-3">No digest yet for this week.</p>
              <button onClick={generate} disabled={generating} className="btn-primary">
                {generating ? 'Generating...' : 'Generate Now'}
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
